### PR TITLE
pushing initial pass at readme

### PR DESCRIPTION
**Pull request by 0xTranqui**

### CODE REVIEW

**Comment by 0xTranqui** [comment]
@1ifeworld/core first pass at week 1 readme. definitely kinda mid, and we need to follow up with local dev instructiosn for frontend, backend, and protocol repos (will be nice for solidifying the internal knowledge weve gotten in the notion the past few days). could also use some spciing up if we want it to be a bit more vibey, but tbh i think the relative plainess is nice

**Review by salieflewis — COMMENTED** [review]
I feel like the first sentence could just read: River facilitates the organization of onchain information.

**Comment by salieflewis** [comment]
What are you imagining the more details re: getting involved would include?

**Review by salieflewis — APPROVED** [review]

**Comment by salieflewis** [comment]
> What are you imagining the more details re: getting involved would include?

Also maybe we should explicitly mention that the protocol repository is separate with its own issues?

**Comment by 0xTranqui** [comment]
> What are you imagining the more details re: getting involved would include?

a plan for how/when we envision getting people involved

**Comment by salieflewis** [comment]
> > What are you imagining the more details re: getting involved would include?
> 
> a plan for how/when we envision getting people involved

Werd. Def feel like we should start thinking about this.

**Comment by 0xTranqui** [comment]
> > What are you imagining the more details re: getting involved would include?
> 
> Also maybe we should explicitly mention that the protocol repository is separate with its own issues?

yea i think explicitly would be nice, it does get linked out in this which I think is ok for now but yea, down for a more robust explanation of the sturcture

**Pull request merged**
