### PR TITLE
Salief/add color system

### PR DESCRIPTION
**Pull request by salieflewis**
Take a look at our stylesheet and tailwind config. Does this feel roughly accurate in terms of establishing a naming convention?

If you have other suggestions let me know. I think the Zord one makes sense given we'll need to introduce things like error states and warning states. I do feel like I assigned the values a bit arbitrarily though. So please give me some guidance as to what may feel more appropriate.

cc: @ioeylim

### CODE REVIEW

**Comment by 0xTranqui** [comment]
some thoughts from looking things over

1. any particular reason to move to HSL rather than HEX? feel like we are generally more comfortable with hexcode so curious as to the reasons behind the switch. after further review Im seeing we have some things in HSL and some things in HEX. feel like we should definitely not be doing that
2. what does this syntax mean:`hsl(var(--accent) / <alpha-value>)'`
3. can you explain reasoning / provide references for putting tailwind config (and tsconfig for that matter) into an external package library that is pulled into our app? is there a reason we dont want it in the app itself? do we get something out of this? mentioning cause dont think I've seen that before
4. we need to consolidate the colors names. for instances when we need multiple shades of the same color, I think a would prefer we top level color definition and then subnames like done in the [entropy style sheet](https://github.com/calebguy/entropy-web/blob/main/packages/tailwind-config/tailwind.config.js)

**Comment by salieflewis** [comment]
> some thoughts from looking things over
> 
> 1. any particular reason to move to HSL rather than HEX? feel like we are generally more comfortable with hexcode so curious as to the reasons behind the switch. after further review Im seeing we have some things in HSL and some things in HEX. feel like we should definitely not be doing that
> 2. what does this syntax mean:`hsl(var(--accent) / <alpha-value>)'`
> 3. can you explain reasoning / provide references for putting tailwind config (and tsconfig for that matter) into an external package library that is pulled into our app? is there a reason we dont want it in the app itself? do we get something out of this? mentioning cause dont think I've seen that before
> 4. we need to consolidate the colors names. for instances when we need multiple shades of the same color, I think a would prefer we top level color definition and then subnames like done in the [entropy style sheet](https://github.com/calebguy/entropy-web/blob/main/packages/tailwind-config/tailwind.config.js)

1. I've just been reading that HSL is more accurate on the web. Also was a recommendation from the snippets of Refactoring UI I've been reading. This PR was a bit unclear/also because it is in draft form, but once we figure out the color system my plan is to go through and wipe the codebase of existing hex code references.
2. The syntax is just saying, take the CSS variable `accent` and render it in the hsl color space. Not too sure about `alpha-value`, this is straight from the Tailwind docs.
3. It allows us to share the same Tailwind config amongst our apps. So in this case both the design system docs and River itself. The tsconfig is the same principle, it should stretch to the backend too, although I don't think it does at the moment.
4. What you're suggesting is what I proposed a bit earlier on GitHub, but I think it is a little limiting. Trying to strike a balance though, because that example is easy and legible yes, just also trying to think of something that will scale.

**Comment by ioeylim** [comment]
Yeah all of this checks out to me, but curious if we want to even further abstract it away from primary/secondary naming conventions. Wonder what you thought about going from grey-1 to grey-6 (or some kind of general logic like that) and then grouping the different grey styles together on estuary for the complete component style (ie. button, input field, etc)

**Comment by jawndiego** [comment]
the only other naming convention i can think of is perhaps something like this:

base: default starting point 
inverse: for things that need to contrast sharply from base 
muted: lighter variants for secondary or tertiary content. could even do something like muted-whisper, muted-mumble, muted-talk 
highlight: color used to draw attention without indicating success or error. highlight-hint, highlight-alert, etc
positive: for success
negative: for errors or warnings

**Comment by salieflewis** [comment]
Estuary_-_River_-_2023-09-06_11 54 01

Here is the system I implemented based on all your feedback as well as guidance from other design systems. I believe that this will allow us to scale the system over time, easily being able to add functional colors if we so choose, as well as establish a general system for building components quickly.

Essentially `base` is just our background color. `label` refers to our typography, and `accent` is well, accent.

cc: @1ifeworld/core 

It is going to be a bit annoying to port everything over to this system, I've begun doing this in the PR, but didn't do it very thoroughly, nor do any of the shadcn stuff outside of the `Dialog` component background.

Please relay questions and concerns!

**Comment by salieflewis** [comment]
Resolves #51

**Review by jawndiego — APPROVED** [review]

**Pull request merged**
