### PR TITLE
Salief/add auth component

### PR DESCRIPTION
**Pull request by salieflewis**
Wanted to note that based on ConnectKit's [API Reference](https://docs.family.co/connectkit/api-reference#api-reference) it doesn't look like there is a way to just immediately disconnect on first click without going through their prescribed modal. Maybe something to keep in mind surrounding the designs. But also maybe I missed something so if y'all want to look over the documentation that'd be helpful!

cc: @ioeylim

### CODE REVIEW

**Comment by salieflewis** [comment]
There is something going on with Vercel that this branch is not getting deployed :/

**Comment by ioeylim** [comment]
yeah the vercel deploy is not showing the changes. 

re: ConnecKit disconnect. I found [here](https://docs.family.co/connectkit/connect-button#connect-button-render-props-specification) a hide function for the modal but couldn't find how to specifically disconnect the wallet with our native disconnect button. checked foundation.app and it looks like they are able to do it.

**Review by 0xTranqui — APPROVED** [review]
big fan of the Connect and AuthDropdown components you added. I feel like maybe could be worth splititng out the auth dropdown to its own compnent, but kind of like it being in the same file as the Connect component since I imagine this is the only place where we need to grab that funcitonality?

im going to approve + merge this right now so I can access the web3 functionality you added, in but one thing you might be able to adjust is accessing the connect modal open/close api directly via the wagmi 'useDisconnect' hook. that is how we managed it in the seeknoevil site and didnt have problems with disconnect issues -- here's the link to where this is implemented (via the useAuth hook) in [seeknoevil](https://github.com/0xTranqui/seeknoevil/blob/master/src/components/auth/Connect.tsx)

cc: @salieflewis just in case

**Comment by 0xTranqui** [comment]
believe I may have caught an error post merge? it looks like the doubling up of the children (see screenshot below) might be causing duplicative renders of all the sites contents (see screenshot at end) ??

Screenshot 2023-08-29 at 1 11 52 AM

Screenshot 2023-08-29 at 1 13 36 AM

**Pull request merged**
