### PR TITLE
Jawn/rest of crud

### PR DESCRIPTION
**Pull request by jawndiego**
CRUD OPERATIONS 

DataSent (missing associated listing metadata) 
DataRemoved 
PressRegistered
AccountRolesSet
MerkleRootSet

### CODE REVIEW

**Comment by jawndiego** [comment]
@salieflewis @0xTranqui

**Comment by jawndiego** [comment]
im not sure why vercel deployment failed. didnt change anything between commit [2fe9329](https://github.com/1ifeworld/river/pull/43/commits/2fe93293d48ab7085f58d717e43cf0dd9aa76892) and [4b43dc8](https://github.com/1ifeworld/river/pull/43/commits/4b43dc8a91d6f70f1d16beccfac0af178dbfd9f0) other than adding a .env.example

**Comment by jawndiego** [comment]
weird. just pressed 'redeploy' on vercel and the it deploys now.

**Comment by salieflewis** [comment]
> weird. just pressed 'redeploy' on vercel and the it deploys now.

Sometimes it is like that, weird.

**Comment by salieflewis** [comment]
Resolves #33

**Comment by jawndiego** [comment]
i'm including Router as a redundancy atm just in case 1. im missing something in the other entities and as a catch all. we could remove it if its not necessary and properly covered via the other entities. 

good call on 1. though and am separating them out.

**Review by salieflewis — APPROVED** [review]

**Pull request merged**
