### PR TITLE
resolves issues #61 #62 #63 #70

### PR DESCRIPTION
**Pull request by jawndiego**
solves #61 #62 #63

### CODE REVIEW

**Comment by salieflewis** [comment]
Ready for review? Also if you include `Resolves` in your comment or commits, it will close the issue(s) when this gets merged in.

cc: @jawndiego

**Comment by jawndiego** [comment]
solves #61 #62 #63 and #70

**Comment by salieflewis** [comment]
> solves #61 #62 #63 and #70

I think it is in the comments that it needs to be... but the title might work to.

**Review by salieflewis — CHANGES_REQUESTED** [review]
When do entity fields need to be required and when do they not need to be? 

If `RiverOperations` is a wall of comments shouldn't we just get rid of it?

We should be more specific when naming the type `OurNftStructure`.

Are `useGetNFTMetadata` and `useGetTokenMetadata` the same hook? If so they should have the same name. And this is a nit but this PR shouldn't extend to include that hook in the frontend dir (I don't actually care if you keep it in, I know we need it on the frontend as well).

If the naming convention for the Ponder stuff is file = event name, we should be consistent to the logic file as well.

In `pressDataDecoder` the arg type should be Hex I believe (the address type) and why do you have to type the bytecode as any? Doesn't viem infer the return type?

Have we tested the string data decoding on multiple strings? What exactly is it doing?

**Comment by jawndiego** [comment]
great comments. addressed all of them. i agree with the front end bit. it was copied from max code and i left it there and pushed it. they are *slightly* different because the front end hook uses useState and other things from react. so i named it something different to distinguish them, but changed it back so they match names.

**Comment by salieflewis** [comment]
I think this Vercel error is my fault, I've got look at this more closely tmrw. I've been running into deploy errors as well that are the exact same as this.

CleanShot 2023-08-30 at 00 27 50@2x

**Review by salieflewis — APPROVED** [review]

**Comment by salieflewis** [comment]
This is good to go. If there is an error when main builds, just redeploy it directly on Vercel.

cc: @jawndiego

**Review by 0xTranqui — APPROVED** [review]
this is so awesome. I think there could be one optimization in the DataSent.ts file to enable us to avoid fetching target nft metadata for a listing if we've already fetched it before -- by moving the code related to the fetching of the metadata underneath the if check for if that listing id (network/targetAddress/id) has already been added before

**Pull request merged**
