### PR TITLE
created initial card comp in design system, initial opinoated channel…

### PR DESCRIPTION
**Pull request by 0xTranqui**
… card comp based off entity card comp, and initial itnegration into home page

### CODE REVIEW

**Comment by ioeylim** [comment]
Leaving a few comments so that there's a few quick edits you can jump back into with.
 
1. "Creator" text (tranqui.eth) should be (#777777) and the line height between the title needs to be bit shorter (not exactly sure how much)
2. Remove the current hover state zoom-in animation. If you want to change it to the correct one, it can be found [here](https://www.figma.com/file/vq8D56Fddhysfv24raCmL1/River?type=design&node-id=41%3A4847&mode=design&t=SoL7SYXraNpzY8eV-1). 
3. Change font to Helvetica Neue

**Comment by 0xTranqui** [comment]
@salieflewis going to incorporate Joeys's feedback into a larger PR ill be putting up soon for the modal

**Comment by 0xTranqui** [comment]
Definitely somewhat arbitrary what shadcn code I used for this. Context menu is what was used in this card component on the shadcn music [example](https://ui.shadcn.com/examples/music) and looked nice, but feels a bit overkill for what this is. Do you have a diff suggestion for how to choose what we take from shadcn?

Screenshot 2023-08-28 at 10 40 00 AM

**Comment by salieflewis** [comment]
> Definitely somewhat arbitrary what shadcn code I used for this. Context menu is what was used in this card component on the shadcn music [example](https://ui.shadcn.com/examples/music) and looked nice, but feels a bit overkill for what this is. Do you have a diff suggestion for how to choose what we take from shadcn?
> 
> Screenshot 2023-08-28 at 10 40 00 AM

In case it wasn't clear, the reason `ContextMenu` is being used in this instance is explicitly because it allows the right-click functionality on the cards.

**Comment by 0xTranqui** [comment]
> > Definitely somewhat arbitrary what shadcn code I used for this. Context menu is what was used in this card component on the shadcn music [example](https://ui.shadcn.com/examples/music) and looked nice, but feels a bit overkill for what this is. Do you have a diff suggestion for how to choose what we take from shadcn?
> > Screenshot 2023-08-28 at 10 40 00 AM
> 
> I think we need Joey to weigh in here, cause the Figma I linked is confusing. If it wasn't a `ContextMenu` it should either just be a raw Image component native from Next or potentially an `AspectRatio` instance.
> 
> cc: @ioeylim

imo the larger question is when to reach to shadcn for code vs not. having never used something like this before, I feel like im making totally arbitrary decisions.

**Comment by ioeylim** [comment]
> > > Definitely somewhat arbitrary what shadcn code I used for this. Context menu is what was used in this card component on the shadcn music [example](https://ui.shadcn.com/examples/music) and looked nice, but feels a bit overkill for what this is. Do you have a diff suggestion for how to choose what we take from shadcn?
> > > Screenshot 2023-08-28 at 10 40 00 AM
> > 
> > 
> > I think we need Joey to weigh in here, cause the Figma I linked is confusing. If it wasn't a `ContextMenu` it should either just be a raw Image component native from Next or potentially an `AspectRatio` instance.
> > cc: @ioeylim
> 
> imo the larger question is when to reach to shadcn for code vs not. having never used something like this before, I feel like im making totally arbitrary decisions.

1. Context menu could be nice eventually, but I think the same action can be already achieved on hover and clicking on the horizontal-circle icon. (For now, I can't really even think of what we would need on the menu anyway other than "copy address") 
2. Regarding when to and when not to lean into shadcn, I agree that we should just have a coordinated stance on those instances.

**Comment by 0xTranqui** [comment]
@salieflewis fixed the git ignore and changed EntityCard back to ContextMenu. do you want to approve to merge through and then we can make updates to ContextMenu choice elsewhere? or do you want to revisit fully here before pushing

**Comment by salieflewis** [comment]
> @salieflewis fixed the git ignore and changed EntityCard back to ContextMenu. do you want to approve to merge through and then we can make updates to ContextMenu choice elsewhere? or do you want to revisit fully here before pushing

Its weird cause I feel like the .gitignore should extend to a `.env` file. In addition to updating the .gitignore I would just delete the file from the PR before pushing it to main.

In regards to the `ContextMenu` stuff, I don't think it is an integral change that needs to come in this PR, so happy to include it.

**Pull request merged**
