### PR TITLE
parallelization idea

### PR DESCRIPTION
**Pull request by 0xTranqui**

### CODE REVIEW

**Comment by 0xTranqui** [comment]
@jawndiego @salieflewis this is just a rough idea. but I think something like this could work for adding parellization to the dropzone component (and other processes as well!). we could potentially use something like the p-queue import for this type of thing too, which is what the transaction processing I added uses. no reason for us to write our own parellelization + concurrency logic I presume

**Comment by 0xTranqui** [comment]
after thinking about this more, DEFINITELY should use something like p-queue to handle the concurrency and retries and failure modes and all that. u can peep the code in lib/transactions/createNonceManager and lib/transactions/writeContract to see examples of both p-queue and p-retry

**Comment by 0xTranqui** [comment]
also heads up. didnt test the frontend at all. just a code idea

**Comment by 0xTranqui** [comment]
@salieflewis is this helpful to keep up or should I close? are u down to handle parallelization?

**Comment by salieflewis** [comment]
> @salieflewis is this helpful to keep up or should I close? are u down to handle parallelization? can we (one of us 3) prioritize that plz?

I think we should keep it open and make an issue for it. Would be great if you could make that issue.

**Pull request closed without merging**
