### PR TITLE
attempt to type Listing

### PR DESCRIPTION
**Pull request by jawndiego**

### CODE REVIEW

**Comment by 0xTranqui** [comment]
some disparate thoughts after checking out the draft:

1. can we add "createdAt" to the Listing inputs you are typing out [here](https://github.com/1ifeworld/river/blob/jawn/attempt_to_type_Listing/apps/frontend/app/channel/%5Bcontract%5D/page.tsx)? it looks like createdAt is in the type you are defining [here](https://github.com/1ifeworld/river/blob/jawn/attempt_to_type_Listing/apps/frontend/components/channel/ChannelBody.tsx) so should be ok?
2. I feel like having all of these unrequired values in a [type](https://github.com/1ifeworld/river/blob/jawn/attempt_to_type_Listing/apps/frontend/components/channel/ChannelBody.tsx) kind of defeat the purpose of having strong typing. do u have any thoughts @salieflewis? imo it would be cleaner to have them all be required, and then have us get better with our error + null value handling
3. the unique ids used for the postgres seem to be creating extra noise in the types. I would say lets get rid of them but maybe they end up being useful for some reason I can't think of right now
4. anytime an address is references it should be type Hex. it is currently type string in the Listing definition [here](https://github.com/1ifeworld/river/blob/jawn/attempt_to_type_Listing/apps/frontend/components/channel/ChannelBody.tsx). ik i started this bad habit when trying to work through the Add listing
5. confused why we had to get rid of the "?" in the screenshots below. plz explain
Screenshot 2023-09-05 at 9 59 01 PM
 modal, but lets squash it before it proliferates more

**Comment by 0xTranqui** [comment]
oh yea and I knew this was confusing. I had already defined the Listing type for another purpose in the [SearchContainer](https://github.com/1ifeworld/river/blob/bcc044c36abf947cb984c59da0e04dd023fd41cd/apps/frontend/components/client/AddToChannelModal/states/search/SearchContainer.tsx#L19) component. plz reconcile the differences, or keep both but make it clearer the distinct roles each is playing

**Review by 0xTranqui — COMMENTED** [review]
left a bunch of comments outside of this review

**Comment by jawndiego** [comment]
1. done!
2. removed optionality. created a baselisting on your initial typing needed to search. then extended baselistings to include listings as new type. 
3. can take them off leaving them for now just to have, but if too noisy will remove. 
4. addresses are now Hex
5. brought the ? back it should be ?

**Comment by jawndiego** [comment]
There’s some prelim work from another issue. It bled into this branch. It’s an all channel query , it’s associated functions and the generated sdk from it.

**Review by salieflewis — APPROVED** [review]
Why are we introducing another query here, `allChannels`?

Should we begin to collocate these types as expressed in #88 

Whats the justification for the naming convention, `Listing` and `BaseListing`? This is a bit confusing.

**Pull request merged**
