### PR TITLE
salief/update channel view

### PR DESCRIPTION
**Pull request by salieflewis**
- move back to stack
- update channel banner component
- wip, redesign channel page, addresses text overflow

https://www.loom.com/share/e02ebde1f79a46c0a2856805a586c140

### CODE REVIEW

**Comment by ioeylim** [comment]
1. I think we can limit the number of channels to 50 on the list (which is approximately the length of the page and some buffer for larger screens). Perhaps there is a "..." or "more" button at the end of the 50 that extends the list by another 50, but for now 50 channels seems good to me. 

2. I personally like the sticky header, but it makes me wonder how we should treat the marquee. First thought was to treat the marquee like content on the page, so that it is not a part of the sticky header. But realizing that that logic might not actually be consistent across the pages (ex. homepage). So in essence (ha), maybe a sticky header with a background that includes the marquee might be the best approach (like the ssense homepage)? Rationale for including the marquee as the header is to provide some consistent look + feel across pages that could feel a little bit dense or chaotic otherwise. 

3. For the channel list styling, I think I'm going to defer making an opinion/decision for a tiny bit  I went into Figma and tried a 10px font, softer black, spacing, etc - but the conclusion was that there's some additional spacing refinement in the deploy that I feel like needs to come before making a more informed decision. But I hear and share the sentiment about the underline hover (just noticing other aspects of it). 

4. Speaking of some spacing refinement, I'll leave some comments on figma and get your thoughts on a few things. One that I noticed is that the top-margin of the header on the deploy is actually 12px like on the figma, but there is discrepancy due to how figma calculates the distance between the font and top of the frame. I roughly calculated that to make it match, it would be a 6px margin instead of 12px.

**Comment by 0xTranqui** [comment]
this is so cool. some thoughts

- i think the header that has a  solid background that content flows under is cleaner. esp once we get more of the nav items in there from the redesign
- i dont understand why we dont find a different font if we are being constrained from lack of font weight differentiation. is there nothing else out there? if we dont want to switch fonts, i think the new reader stylistic marker could be nice for showing what channel your in. 
- i think figuring out the scroll patterns is a big thing that could make the ux make more sense. i feel like we want everything locked in place as possible (feeling of security), and then only have scroll activated in the places of the screen youd expect/need them (because there is more content then can fit in one spot). perhaps that means locking the channel banner and now you can only scroll the playlist. i think that might be an anti pattern tho. anyways whatever it is, lets be purposeful with that and think itll improve the experience on desktop
- i honestly rlly love how simple the channel view looks like on mobile now. it makes me think even if we bring channel images back, they could be much smaller. but maybe we take this as inspo to embrace no channel images around the whole site for good,
- the role of the home page is really interesting to consider now that you have much better nav ability when in a given channel. no thoughts here yet besides its interesting

**Review by 0xTranqui — APPROVED** [review]
Screenshot 2024-01-13 at 12 48 03 PM

this all looks great to me, only qusetion is can you explain what this code is doing and why you made this change? how does this work not as an async function anymore? @salieflewis

**Comment by salieflewis** [comment]
> Screenshot 2024-01-13 at 12 48 03 PM
> this all looks great to me, only qusetion is can you explain what this code is doing and why you made this change? how does this work not as an async function anymore? @salieflewis

The function is still async, it just implements the new React cache which is designed to work with Server Components. Essentially just creating a memoized version of that function. This is what happens natively with all of our fetch requests thanks to Next.js, but because we're not using fetch here explicitly, this is how we would introduce caching.

**Pull request merged**
