### PR TITLE
Jawn/index

### PR DESCRIPTION
**Pull request by jawndiego**

### CODE REVIEW

**Comment by salieflewis** [comment]
Index seems to be a reserved namespace, what is the alternate name for it

What is the active state of the link when navigating to that route? Is the text just black, does ‘River’ become grey?

What is the ordering logic for these channels?

cc: @1ifeworld/core

**Comment by 0xTranqui** [comment]
> Index seems to be a reserved namespace, what is the alternate name for it
> 
> What is the active state of the link when navigating to that route? Is the text just black, does ‘River’ become grey?
> 
> What is the ordering logic for these channels?
> 
> cc: @1ifeworld/core

1. can we dig into the name space more please? quick search of google + nextjs docs did not give any indication that "index" is reserved namespace. 
2. I think we should put whatever this "directiory/index" is as a dropdown item, not in the header. and then we dont have to deal with this. the only issue with this approach is that the index would be inaccessible to peopel without an account/logged in
3. i think first pass on ordering should be alphabetical, so as to serve as a logical way to find specific entities

**Comment by 0xTranqui** [comment]
another smol nit atm is that this page should have the marquee at the top, as according to these designs in [wip6](https://www.figma.com/file/cfK9f5an0jYUkzjzOjA8Xe/wip6?type=design&node-id=755-994&mode=design&t=WKYkEQWPQryg5NXV-0)

Screenshot 2024-04-15 at 5 23 04 PM

**Comment by jawndiego** [comment]
image

current view // pending user query .. which likely involves fetching all existing ids and associating it with a username then sorting all usernames and printing them in grids.

**Pull request merged**
