### PR TITLE
Salief/update drawer

### PR DESCRIPTION
**Pull request by salieflewis**

### CODE REVIEW

**Review by 0xTranqui — APPROVED** [review]
this is really nice. approving with one small request to fix:

1. see screenshot below for the hover state of the disconnect button on desktop. rn its hover state is not a change of button color, rather an underline of the text in the button. i dont believe this hover state matches our design system, and think would be better served by something like on hover the white bacgkround becomes slightly darker, or something like that. defer to u on the exact impl but think this will be nicer

Screenshot 2023-09-29 at 1 20 31 PM

**Comment by salieflewis** [comment]
> this is really nice. approving with one small request to fix:
> 
> 1. see screenshot below for the hover state of the disconnect button on desktop. rn its hover state is not a change of button color, rather an underline of the text in the button. i dont believe this hover state matches our design system, and think would be better served by something like on hover the white bacgkround becomes slightly darker, or something like that. defer to u on the exact impl but think this will be nicer
> 
> Screenshot 2023-09-29 at 1 20 31 PM

I understand the confusion. The reason its like that is because its not actually a button, but rather part of the dropdown content. When its alone and centered it looks exactly like a button. We could potentially tuck the link to the feedback route here, and align the text left again. This would probably make the underline hover states more clear. Also the icons would definitely help. The `IconContainer` component in Estuary needs to be updated and thats coming in a separate PR.

cc: @0xTranqui

**Comment by 0xTranqui** [comment]
why dont we just make it a button?

or if we dont want it to be a button, can we please remove the outerr border? or move to something that isnt an underline, like bolding the for example. the current implemnetation is off putting and doesnt give feeling of confidence on button click i want when disconnecting.

in the short term tho, I would prefer we have a work around since pushing the exact impl as it exists I think is confusing

**Comment by salieflewis** [comment]
> why dont we just make it a button?
> 
> or if we dont want it to be a button, can we please remove the outerr border? or move to something that isnt an underline, like bolding the for example. the current implemnetation is off putting and doesnt give feeling of confidence on button click i want when disconnecting.
> 
> in the short term tho, I would prefer we have a work around since pushing the exact impl as it exists I think is confusing

Think I figured out what needed to be done. Icons will definitely help with this approach as well, but I was just missing using the `DropdownMenuItem` component.

cc: @0xTranqui

**Pull request merged**
