### PR TITLE
Jawn/i#33

### PR DESCRIPTION
**Pull request by jawndiego**
Added all event creates for:
### IdRegistry

**Events**

- Attest
- RevokeAttestation
- TransferCancelled
- TransferComplete
- TransferInitiated

### Delegate

**Events**

- Delegate

### RiverValidator

**Events**

- Validate
- OperatorUpdated

### CODE REVIEW

**Review by 0xTranqui — COMMENTED** [review]
few comments after a quick scan. ik we talked about getting the foundation set before starting on the logic, so aware u were prolly not worrying bout these on the first pass

1. the revokeAttestation event should not create a new row in the IdRegistry entity, rather clear the value of an existing id previously created by Attestation. not exactly sure what the crud should be but at the end, the `attesetor` value should be zero address

2. I think a more effective way to handle id transfer events should be something like using a Transfer specific entity, creating a new row on `initiateTransfer` events, and clearing that row (which signals pending transfers) on `cancelTrasnfer` or `acceptTransfer` events. not sure how we can preserve historical data in here, but wed want to do that as well to be able to trace ownership history

3. I think the Validate event in river validator should be an upsert rather than a create, that will update the field of 'status`, creating the row if the status for an id has been updated to true (everything defaults to false), while resetting it to false if the status was set to false

also in terms of the id fields for basically all entitieis, im pretty sure we want to follow the pattern of {originChain}/{originContract}/{entitySpecificValues} to preserve flexibility of chains + contracts in use for all events. I think some/most of the entities have this but not all

**Comment by 0xTranqui** [comment]
@jawndiego i dont think RevokeAttestation should ever be a create. its impossible to call unless that row has already been created by a previous Atteset event. will only ever be clearing an existing attestation

**Comment by jawndiego** [comment]
> few comments after a quick scan. ik we talked about getting the foundation set before starting on the logic, so aware u were prolly not worrying bout these on the first pass
> 
> 1. the revokeAttestation event should not create a new row in the IdRegistry entity, rather clear the value of an existing id previously created by Attestation. not exactly sure what the crud should be but at the end, the `attesetor` value should be zero address
> 2. I think a more effective way to handle id transfer events should be something like using a Transfer specific entity, creating a new row on `initiateTransfer` events, and clearing that row (which signals pending transfers) on `cancelTrasnfer` or `acceptTransfer` events. not sure how we can preserve historical data in here, but wed want to do that as well to be able to trace ownership history
> 3. I think the Validate event in river validator should be an upsert rather than a create, that will update the field of 'status`, creating the row if the status for an id has been updated to true (everything defaults to false), while resetting it to false if the status was set to false
> 
> also in terms of the id fields for basically all entitieis, im pretty sure we want to follow the pattern of {originChain}/{originContract}/{entitySpecificValues} to preserve flexibility of chains + contracts in use for all events. I think some/most of the entities have this but not all


think its worth keeping track of initiate + cancel events as separate rows. while using Transfer complete to update the fields. updated the rest of the events based on feedback.

**Comment by 0xTranqui** [comment]
'think its worth keeping track of initiate + cancel events as separate rows. while using Transfer complete to update the fields. updated the rest of the events based on feedback.'

arent cancel + complete affectively doing the same thing -- which is updating the status of a row created via the initiate event? im all for tracking every event separately if its helpful btw, just thinking of what api we are hitting to get the transfer status of a given id (and i think i could see how a Transfers entity that gets new rows made on initiate events, and existing rows cleared on cancel or complete events could work)

**Comment by 0xTranqui** [comment]
> think its worth keeping track of initiate + cancel events as separate rows. while using Transfer complete to update the fields. updated the rest of the events based on feedback.

arent cancel + complete affectively doing the same thing -- which is updating the status of a row created via the initiate event? im all for tracking every event separately if its helpful btw, just thinking of what api we are hitting to get the transfer status of a given id (and i think i could see how a Transfers entity that gets new rows made on initiate events, and existing rows cleared on cancel or complete events could work)

**Comment by jawndiego** [comment]
> arent cancel + complete affectively doing the same thing -- which is updating the status of a row created via the initiate event? im all for tracking every event separately if its helpful btw, just thinking of what api we are hitting to get the transfer status of a given id (

going to break this down via issues for a separate PR

**Pull request merged**
