### PR TITLE
add channel details component

### PR DESCRIPTION
**Pull request by salieflewis**

### CODE REVIEW

**Comment by ioeylim** [comment]
This is lit. 

Should we fix the vertical position of the channel details when there is not enough items to scroll?

**Comment by salieflewis** [comment]
> This is lit.
> 
> Should we fix the vertical position of the channel details when there is not enough items to scroll?

My thinking was that the details would be placed proportionally to the last item, and appear higher on the page if there weren't many items. Kind of like this:

builder_utils_issues

However I think it could be argued that it does look weird in a channel with 0 items.

cc: @ioeylim

**Comment by 0xTranqui** [comment]
@salieflewis @ioeylim why dont we just have the item count not show up when theres 0 items? but still show the "channel created x hours ago" in that proprtional height salief was describing

**Comment by salieflewis** [comment]
> @salieflewis @ioeylim why dont we just have the item count not show up when theres 0 items? but still show the "channel created x hours ago" in that proprtional height salief was describing

I personally like the indication of zero items.

**Comment by ioeylim** [comment]
> > @salieflewis @ioeylim why dont we just have the item count not show up when theres 0 items? but still show the "channel created x hours ago" in that proprtional height salief was describing
> 
> I personally like the indication of zero items.

I also like 0 items, and upon second look I don't think I mind it. So you can disregard my initial comment. 

Screenshot 2024-01-15 at 6 04 43 PM

**Pull request merged**
